### ISSUE TITLE
Navigation bar likes to reverse it self

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#127] opened 2015-10-29 06:49 UTC
looks like the default is Urdu/Arabic style (right to left) ...
found at least 10 different ways in English to have  "Logout" first and "My Home" last (Bell Installer for Windows 1.0.55)

please assume left to right is default never wanna be able to break that order ....

**Comment by SabaBaig** [comment] 2015-10-30 06:00
Stefan it would be great if you please list down the ways, following which you faced this issue.

**Comment by SabaBaig** [comment] 2015-11-03 10:27
Stefan this issue turns out to be removed in the result of solving issue#126. So we are unable to reproduce it.But if its still appearing at your end. Then let me know.

**Comment by SabaBaig** [comment] 2015-11-19 10:22
This issue is resolved now and its available on following URLs.
https://github.com/open-learning-exchange/BeLL-Apps/commit/6a3ef55c7948a579e4c24a7b133d8e578b141442
https://github.com/open-learning-exchange/BeLL-Apps/commit/108ea3b746ed28ee97ec84b30effc0e2276d832c   (After resolving merge conflicts in views/Dashboard.js)

**Closed** 2015-12-11 20:26 UTC
Labels: bug
